// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonDirectoryWebApi.DbContexts;

#nullable disable

namespace PersonDirectoryWebApi.Migrations
{
    [DbContext(typeof(PersonApiContext))]
    partial class PersonApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PersonDirectoryWebApi.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tbilisi"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Batumi"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kutaisi"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Rustavi"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Gori"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Zugdidi"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Poti"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Kobuleti"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Khashuri"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Telavi"
                        });
                });

            modelBuilder.Entity("PersonDirectoryWebApi.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            DateOfBirth = new DateTime(1997, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Tato",
                            GenderId = 1,
                            ImagePath = "DefaultPath which will change after uploading photo",
                            LastName = "Topuria",
                            PersonalNumber = "00000000000"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            DateOfBirth = new DateTime(1997, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sophio",
                            GenderId = 2,
                            ImagePath = "DefaultPath which will change after uploading photo",
                            LastName = "Khopheria",
                            PersonalNumber = "00000000000"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 1,
                            DateOfBirth = new DateTime(1993, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mikheil",
                            GenderId = 1,
                            ImagePath = "DefaultPath which will change after uploading photo",
                            LastName = "Topuria",
                            PersonalNumber = "00000000000"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 2,
                            DateOfBirth = new DateTime(1993, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Dea",
                            GenderId = 2,
                            ImagePath = "DefaultPath which will change after uploading photo",
                            LastName = "Tvildiani",
                            PersonalNumber = "00000000000"
                        });
                });

            modelBuilder.Entity("PersonDirectoryWebApi.Entities.PhoneNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NumberTypeId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumbers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("PhoneNumbers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NumberTypeId = 1,
                            PersonId = 1,
                            PhoneNumbers = "555159015"
                        },
                        new
                        {
                            Id = 2,
                            NumberTypeId = 2,
                            PersonId = 1,
                            PhoneNumbers = "555555555"
                        },
                        new
                        {
                            Id = 3,
                            NumberTypeId = 3,
                            PersonId = 1,
                            PhoneNumbers = "588888888"
                        },
                        new
                        {
                            Id = 4,
                            NumberTypeId = 1,
                            PersonId = 2,
                            PhoneNumbers = "599999999"
                        },
                        new
                        {
                            Id = 5,
                            NumberTypeId = 1,
                            PersonId = 3,
                            PhoneNumbers = "599999998"
                        },
                        new
                        {
                            Id = 6,
                            NumberTypeId = 3,
                            PersonId = 3,
                            PhoneNumbers = "599999997"
                        },
                        new
                        {
                            Id = 7,
                            NumberTypeId = 1,
                            PersonId = 4,
                            PhoneNumbers = "599999996"
                        });
                });

            modelBuilder.Entity("PersonDirectoryWebApi.Entities.RelatedPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("RelationTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("RelatedPersons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Irakli",
                            LastName = "Giorgadze",
                            PersonId = 1,
                            RelationTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Nikoloz",
                            LastName = "Bezhitashvili",
                            PersonId = 1,
                            RelationTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Nino",
                            LastName = "Darsavelidze",
                            PersonId = 2,
                            RelationTypeId = 2
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Temuri",
                            LastName = "Tvildiani",
                            PersonId = 3,
                            RelationTypeId = 3
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Tamta",
                            LastName = "Mtchedlishvili",
                            PersonId = 4,
                            RelationTypeId = 4
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Giorgi",
                            LastName = "Kopadze",
                            PersonId = 4,
                            RelationTypeId = 2
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Giorgi",
                            LastName = "Megreli",
                            PersonId = 1,
                            RelationTypeId = 1
                        });
                });

            modelBuilder.Entity("PersonDirectoryWebApi.Entities.Person", b =>
                {
                    b.HasOne("PersonDirectoryWebApi.Entities.City", "City")
                        .WithMany("Persons")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("PersonDirectoryWebApi.Entities.PhoneNumber", b =>
                {
                    b.HasOne("PersonDirectoryWebApi.Entities.Person", "Person")
                        .WithMany("Numbers")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("PersonDirectoryWebApi.Entities.RelatedPerson", b =>
                {
                    b.HasOne("PersonDirectoryWebApi.Entities.Person", "Person")
                        .WithMany("Relatives")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("PersonDirectoryWebApi.Entities.City", b =>
                {
                    b.Navigation("Persons");
                });

            modelBuilder.Entity("PersonDirectoryWebApi.Entities.Person", b =>
                {
                    b.Navigation("Numbers");

                    b.Navigation("Relatives");
                });
#pragma warning restore 612, 618
        }
    }
}
